export const Marquee = {
	first: {
		'1': require('./1-min.jpg'),
		'2': require('./2-min.jpg'),
		'3': require('./3-min.jpg'),
		'4': require('./4-min.jpg'),
		'5': require('./5-min.jpg'),
		'6': require('./6-min.jpg'),
		'7': require('./7-min.jpg'),
		'8': require('./8-min.jpg'),
		'9': require('./9-min.jpg'),
		'10': require('./10-min.jpg'),
	},
	second: {
		'11': require('./11-min.jpg'),
		'12': require('./12-min.jpg'),
		'13': require('./13-min.jpg'),
		'14': require('./14-min.jpg'),
		'15': require('./15-min.jpg'),
		'16': require('./16-min.jpg'),
		'17': require('./17-min.jpg'),
		'18': require('./18-min.jpg'),
		'19': require('./19-min.jpg'),
		'20': require('./20-min.jpg'),
	},
	third: {
		'21': require('./21-min.jpg'),
		'22': require('./22-min.jpg'),
		'23': require('./23-min.jpg'),
		'24': require('./24-min.jpg'),
		'25': require('./25-min.jpg'),
		'26': require('./26-min.jpg'),
		'27': require('./27-min.jpg'),
		'28': require('./28-min.jpg'),
		'29': require('./29-min.jpg'),
		'30': require('./30-min.jpg'),
	}
}